### ISSUE TITLE
Users of this library are causing DDoS against GerritHub.io

### ISSUE THREAD

**Issue by lucamilanesio** [uwolfer/gerrit-rest-java-client#107]
We start receiving a lot of authentication requests looping and generating traffic from multiple IPs to GerritHub.io.

I believe the problem is associated to the way the authentication is managed in the library.
See the [culprit of the problem](https://github.com/uwolfer/gerrit-rest-java-client/blob/01c39a053ac000f31f5e61764a6adec4235eac6a/src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java#L332).

The problem is that the client assumes that a non-50x and non-401 is a successful authentication. However, when people are using GerritHub.io, the login would bring them to the OAuth handshake after having requested the authentication scope to apply.

The form-based authentication won't work at all from an API perspective. The library should detect this situation and fallback to the regular basic authentication of the REST-API, which would use the username/password generated in Gerrit rather than OAuth.

**Comment by uwolfer** [comment]
@lucamilanesio: Do you think this is a "new" issue?

Does it affect all users who are using this lib (for example by using the Gerrit plugin)?

Do you already have a possible fix in mind?

I'm a bit scarred of changing authentication stuff because it is a big fragile as far as I remember (especially for supporting the "xGerritAuth" stuff).

**Comment by lucamilanesio** [comment]
> @lucamilanesio: Do you think this is a "new" issue?

No, I believe it has been there for years. I need to understand why it was triggered today: possibly someone using your library pushed an update? It wasn't coming from a specific IP, but all of them had `gerrit-rest-java-client/0.8.16 using Apache-HttpClient/4.5.6` in their user-agent.

> Does it affect all users who are using this lib (for example by using the Gerrit plugin)?

Affects only the ones using Ver. 0.8.16.

> Do you already have a possible fix in mind?

Yes, it should be fairly easy I believe. The OAuth handshake redirection could be used as a way to detect this situation.

> I'm a bit scarred of changing authentication stuff because it is a big fragile as far as I remember (especially for supporting the "xGerritAuth" stuff).

The X-GerritAuth cookie is a bit tricky indeed, I know.

**Comment by lucamilanesio** [comment]
I just double-checked the logs, and it looks like the anomaly is NOT associated to other versions of the library, but only with `v0.8.16`. It could also be associated with wrong usage of the library, so I could look at other projects using it.

The IntelliJ plugin uses the `v0.8.16` but has a slightly different user-agent. I would therefore exclude that plugin. The [Gerrit Code Review pllugin for Jenkins](https://github.com/jenkinsci/gerrit-code-review-plugin/blob/0425f0ea79e1c164d56ace75bc5cde0c07880e8b/pom.xml#L364) uses the `v0.8.15`, so that one is excluded as well.

**Comment by uwolfer** [comment]
@lucamilanesio: I've just looked into the git log v0.8.16..v0.9.1 and I cannot find any commit which could have fixed this issue... Can you find users in the logs which use a newer version of lib and are not suffering from this issue? And can you find v0.8.16 users which seem not to have this issue in the logs?

**Comment by lucamilanesio** [comment]
By digging into a wider set of logs, I see the problem coming from two versions: `v0.8.13` and `v0.8.16`. I do see calls that are using the `v0.8.16` and do not have the issue, but they use the REST-API authentication mechanism.

I believe the problem is exactly *how* this library is used rather than the library itself. This problem that I believe I have identified is basically a missed status code in the reasons of an authentication failure.  If you try to perform an authentication request using the login URL `/login` you may actually receive a `302` which *isn't* a good response but a request to authentication with an external `OAuth 2.0` provider. That should be detected as a failure in the authentication process rather than a success.

Of course, depending on who is using this library, the error could be detected anyway in other ways (e.g. the authenticated APIs are still failing) but it would be best IMHO to have this condition detected explicitly and return a failure to the client.

**Comment by lucamilanesio** [comment]
I have attempted a fix to the problem, let me know if you agree on the approach.
I will then announce on to the GerritHub.io users that they will *have to upgrade* to the new version of the REST Client to continue using the service.
