### ISSUE TITLE
code-review +1 how to do it

### ISSUE THREAD

**Issue by HwangChan** [uwolfer/gerrit-rest-java-client#118]
sorry，man，My english is not very good,but i encountered some problems;
i want to do like `ssh -p 29418 huangc4@10.16.37.120 gerrit review 17,1  --code-review +1`

--code-review 1
but i dont know how to use this library to do it，thx

I'm sorry to bother you.

**Comment by uwolfer** [comment]
Hi @hongkailiu 

I think you are looking for something like the following snippet:

gerritApi.changes().id(changeId).revision(revision).review(reviewInput);

Please let me know if this does not help.
