### ISSUE TITLE
Content: "--query2" is not a valid option

### ISSUE THREAD

**Issue by magaofei** [uwolfer/gerrit-rest-java-client#132]
When I use the query method, it fails.

I found this code in `GroupRestClient.java`
```
if (!Strings.isNullOrEmpty(queryRequest.getQuery())) {
            // param is "query2", not "query".
            query = UrlUtils.appendToUrlQuery(query, "query2=" + queryRequest.getQuery());
        }
```
Why is `query2` written here? If `query2` is used, an error will be reported, and `query` will not be wrong. The version of gerrit I use is 3.3.1

**Comment by uwolfer** [comment]
Interesting catch.

I've found the following [here](https://www.gerritcodereview.com/3.2.html):

> Query Groups API accepts the query as parameter for groups filtering, instead of the query2 which was a temporary name given to avoid clashes with an earlier deprecated parameter.

So yes, I think we should change it back to `query` (and probably break it for older Gerrit servers).

**Comment by EFregnan** [comment]
@magaofei, would you like to do this change?

**Comment by magaofei** [comment]
> @magaofei, would you like to do this change?

@EFregnan Okay, should I add a `query` method or replace `query2` with `query`?

**Comment by EFregnan** [comment]
@magaofei , thank you for taking care of it.

Yes, I think it would be fine to simply replace `query2` with` query` in the existing method. 
If I understood correctly, I think this is what @uwolfer meant. 

I wonder if we should also add a comment specifying the latest version of Gerrit for which this method will work after the change.

**Comment by uwolfer** [comment]
> @magaofei , thank you for taking care of it.
> 
> Yes, I think it would be fine to simply replace `query2` with` query` in the existing method.
> If I understood correctly, I think this is what @uwolfer meant.

Yes, unless there is a better idea ;)

> I wonder if we should also add a comment specifying the latest version of Gerrit for which this method will work after the change.

That makes sense.
