### ISSUE TITLE
The client cannot retrieve file content if the file name contains "+"

### ISSUE THREAD

**Issue by vitalca** [uwolfer/gerrit-rest-java-client#144]
Hello,

I am using v0.9.3, trying to retrieve files from an unmerged commit.
For all files with "+" in the names I get `com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful. Message: Not Found. Status-Code: 404. Content: Not Found.`

The client performs URL encoding for all file names in `com.urswolfer.gerrit.client.rest.http.changes.FileApiRestClient#requestPath`, and if I copy a URL of the file/content just before diving into Apache HttpClient and perform a `GET` request using `curl` it works as expected.

However, later in `org.apache.http.impl.execchain.ProtocolExec#execute` a method `rewriteRequestURI()` is executed, and properly encoded `%2B` became `+` again:
```java
// Re-write request URI if needed
rewriteRequestURI(request, route, context.getRequestConfig().isNormalizeUri());
```
By default `org.apache.http.client.config.RequestConfig#isNormalizeUri` equals to `true`:
```java
/**
 * Determines whether client should normalize URIs in requests or not.
 * <p>
 * Default: {@code true}
 * </p>
 *
 * @since 4.5.8
 */
public boolean isNormalizeUri() {
    return normalizeUri;
}
```

Is there a workaround?

**Comment by uwolfer** [comment]
Closed with #145.
