### ISSUE TITLE
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool

### ISSUE THREAD

**Issue by dreamerisdoer** [uwolfer/gerrit-rest-java-client#149]
After the program has been running for some time, ConnectionPoolTimeoutException exception occurs.
I guess it is caused by not consuming response correctly in method: GerritRestClient.request().

Possible solution is add the following code in a final block:
`EntityUtils.consumeQuietly(response.getEntity());`

**Comment by uwolfer** [comment]
Do you use specific endpoints for which the body is not consumed? As far as I remember, we consume the body for most operations. Or does this only happen when a request fails?

**Comment by uwolfer** [comment]
@dreamerisdoer: Please see my question above.

**Comment by dreamerisdoer** [comment]
@uwolfer Sorry for late reply. I do requested a lot of files from gerrit that didn't actually exist anymore. After getting a series of 404 errors, 'Timeout waiting for connection from pool' came out. Maybe I should do some checking first to avoid requesting files that no longer exist.

**Comment by uwolfer** [comment]
In case you can still reproduce this issue with the next release, please let me know. I was only able to spot one place which does not consume the response entity. Feel free to check the code as well. Thanks for your report.
