### ISSUE TITLE
Incorrect format request creating within List<ChangeInfo> get(QueryRequest queryRequest) in ChangesRestClient

### ISSUE THREAD

**Issue by themazay** [uwolfer/gerrit-rest-java-client#17]
In all cases we get request string with change id in option 'q'.
But gerrit does not accept triplet (project~branch~changeId) in options section, it only accepts it in URL, just like .../changes/triplet/...
And we get an error about a wrong symbol '~'.

**Comment by uwolfer** [comment]
@themazay: Can you please post your code-parts which cause this issue?

**Comment by themazay** [comment]
The problem is solved. Answer is "The realisation compatible with Gerrit 2.11.x".
But in this case you should state it in release notes.
I will be able to post a code that cause the issue tomorrow. Write if it is not necessary yet, please.

**Comment by themazay** [comment]
private List<ChangeInfo> get(QueryRequest queryRequest) throws RestApiException {
        String query = "";
        if (!Strings.isNullOrEmpty(queryRequest.getQuery())) {
            query = UrlUtils.appendToUrlQuery(query, "q=" + queryRequest.getQuery());
        }
        if (queryRequest.getLimit() > 0) {
            query = UrlUtils.appendToUrlQuery(query, "n=" + queryRequest.getLimit());
        }
        if (queryRequest.getStart() > 0) {
            query = UrlUtils.appendToUrlQuery(query, "S=" + queryRequest.getStart());
        }
        // server version < 2.9, needed for change list paging
        if (!Strings.isNullOrEmpty(queryRequest.getSortkey())) {
            query = UrlUtils.appendToUrlQuery(query, "N=" + queryRequest.getSortkey());
        }
        for (ListChangesOption option : queryRequest.getOptions()) {
            query = UrlUtils.appendToUrlQuery(query, "o=" + option);
        }

        String url = "/changes/";
        if (!Strings.isNullOrEmpty(query)) {
            url += '?' + query;
        }
        JsonElement jsonElement = gerritRestClient.getRequest(url);
        return changesParser.parseChangeInfos(jsonElement);
    }

If we identify a Change with triplet, then this code work well only with Gerrit 2.11.x.

**Comment by themazay** [comment]
GerritRestApiFactory gerritRestApiFactory = new GerritRestApiFactory();
GerritAuthData.Basic authData = new GerritAuthData.BasicGerritAuthData.Basic("http://gerrithost", "gerrit_user", "qoi7RM...p6q8Ku12");
GerritApi gerritApi = gerritRestApiFactory.create(authData);
ChangeApi changeApi = gerritApi.changes().id("ProjectName~master~Iced78421e96a56ac38588b829ae2899c0c124943");
ChangeInfo changeInfo = changeApi.info();

**Comment by uwolfer** [comment]
@themazay: It is possible that loading changes by triple is only supported by newer Gerrit versions. This is not an issue of this library.

If you can find any REST call with works with a triple against an older version of Gerrit, please post it here.
