### ISSUE TITLE
How do I get comments to a file?

### ISSUE THREAD

**Issue by tdrury** [uwolfer/gerrit-rest-java-client#18]
I can see in the REST API that a call is supposed to be made to URL /changes/{change-id}/detail but I don't see in the Java API source where a call is made to get details, but I do see the CommentInfo class in the jar (and the parser and unit test - nice mocking BTW), but I can't figure out how I'm supposed to get the CommentInfo from the Java API.  Any help?

**Comment by forrert** [comment]
I think the API calls you are looking for are the following:

```java
GerritRestApi gerritRestApi = new GerritRestApiFactory().create(/*auth data*/);
ChangeApi change = gerritRestApi.changes().id(changeId); // get the change you're interested in
RevisionApi revision = change.current(); // get the revision you're interested in
Map<String, List<CommentInfo>> comments = revision.comments(); // get all published comments
Map<String, List<CommentInfo>> drafts = revision.drafts(); // get all draft comments for the current user
```

There are a few more methods to retrieve comments, they are all in the ```com.google.gerrit.extensions.api.changes.ChangeApi``` interface.

**Comment by tdrury** [comment]
Thanks, I just figured it out and came back to comment but you beat me to it.

My (groovy) version is:
   gerritRestApi.changes().id(changeId).revision(revisionNumber).comments();
which lets me get all the comments for a specific revision of a change.  The key in the return map is the file in which the comments were made.
