### ISSUE TITLE
get labels for specific review

### ISSUE THREAD

**Issue by tdrury** [uwolfer/gerrit-rest-java-client#19]
I can get the LabelInfo from a ChangeInfo, but this only gives you the last reviews for a merged change.  I'd like to get the reviews for each revision in the patch set.  I think I can get [this information via](https://git.wdf.sap.corp/Documentation/rest-api-changes.html#get-review): 

    GET /changes/{change-id}/revisions/{revision-id}/review

but I don't see any way to fetch it via the Java API.  Is this something that hasn't yet been implemented?

**Comment by uwolfer** [comment]
I don't think this is supported by Gerrit. If I try the url you posted, I always get labels for the most recent revision.

Please reopen this issue if your are sure that you can get this information with Gerrit REST API.
