### ISSUE TITLE
Possibility of getting a new release

### ISSUE THREAD

**Issue by PMooreWand** [uwolfer/gerrit-rest-java-client#224]
Hello @uwolfer,
Just raising if it is possible to get a new release of the project? 
I am releasing some internal code that utilises the recent pull requests. 
No issues if there are no current plans to.
Many thanks.

**Comment by uwolfer** [comment]
Sure, I will try to create a new release in the next days.

**Comment by uwolfer** [comment]
Released 0.9.7.
