### ISSUE TITLE
submit change

### ISSUE THREAD

**Issue by yanbi** [uwolfer/gerrit-rest-java-client#29]
I thought that the java client doesn't support the function of submitting change. (Ref.:https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#submit-change) Could anyone help to implement this? thanks a lot.

**Comment by uwolfer** [comment]
@yanbi: Are you looking for `api.changes().id(...).current().submit()` (`com.google.gerrit.extensions.api.changes.RevisionApi#submit()`)?

**Comment by yanbi** [comment]
Yes! Do you have implemented it already? For my understanding, all the functions executing http method GET work fine, and others related with PUT or POST, I didn't find the way!

**Comment by uwolfer** [comment]
Yes, it is implemented. There are many PUT and POST methods which are working. Things that are not implemented, thrown an exception so you will notice it.

**Comment by yanbi** [comment]
Okay, So it seems that it doesn't work for me. What I got was: 
com.google.gerrit.extensions.restapi.NotImplementedException: Not implemented. 

Could you please write a simple sample, if it's possible. Many thanks for that!

**Comment by uwolfer** [comment]
@yanbi: Can you please post your code (relevant parts) which is not working?

**Comment by yanbi** [comment]
The code likes following, the part of getting the changes works fine. But I can's submit the change after I got it. Many thanks!. Yan
-----------------------------------------------------------------------------------------------------
 GerritRestApiFactory gerritRestApiFactory = new GerritRestApiFactory();
GerritAuthData.Basic authData = new GerritAuthData.Basic("https://example.com/gerrit", "user", "password"");
		  GerritRestApi gerritApi = gerritRestApiFactory.create(authData);
		  try {
			System.out.println("Changes list");
			List<ChangeInfo> changes = gerritApi.changes().query("project:test").get();
			for (ChangeInfo changeinfo :changes){
				System.out.println(" project:"+changeinfo.project+"id:"+changeinfo.id+"Owner: "+changeinfo.owner.name);
			}
			ChangeInfo change=changes.get(0);
			System.out.print("The change's Id to be submitted:"+change.changeId);
			RevisionApi revisionApi=gerritApi.changes().create(change).current();
			SubmitInput in=new SubmitInput();
			in.onBehalfOf="yan";
			revisionApi.submit(in);

**Comment by uwolfer** [comment]
Try `RevisionApi revisionApi=gerritApi.changes().id(change.id).current();` insted of `RevisionApi revisionApi=gerritApi.changes().create(change).current();`.

**Comment by yanbi** [comment]
many thanks!!! It works now!!!
