### ISSUE TITLE
SocketException with multiple requests

### ISSUE THREAD

**Issue by cbaldacin** [uwolfer/gerrit-rest-java-client#39]
Hi there, I'm developing a tool which collects metrics from gerrit and I'm using this library to get access to the gerrit rest api.
The root of my problem is that the endpoint "/changes/<change-id>/comments" is not working according to https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#list-change-comments
(I tested directly in the browser, I know this is not implemented in the current library version).

Then, in order to collect all comments from all patchs I have to query revision by revision:
For each change previously retrieved I perform a new request like bellow so the comments are available: 

`RevisionApi api = gerritApi.changes().id(changeid).revision(revid);
return api.comments();`

It have been working but not quite always, sometimes after some successful requests I got:

o.apache.http.impl.execchain.RetryExec: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://gerrit:80: **The target server failed to respond**
o.apache.http.impl.execchain.RetryExec: Retrying request to {}->http://gerrit:80
o.apache.http.impl.execchain.RetryExec: I/O exception (java.net.SocketException) caught when processing request to {}->http://gerrit:80: Connection reset

I'm wondering that perhaps it might be a gerrit configuration which is preventing requests after some amount.

What do you think?
Regards
Carlos

**Comment by uwolfer** [comment]
The endpoint mentioned should work with Gerrit v2.12. See [this change](https://gerrit-review.googlesource.com/67459).

I have no idea why Gerrit should block requests. Does the situation improve if you add some delay between requests?

**Comment by cbaldacin** [comment]
Thanks, I'll try to request a gerrit update.
I'll have to perform a pull request then, afaik "/changes/[change-id]/comments" it's not implemented, right?
The situation remains pretty much the same adding some delay, it just take more time to throws the exception.

**Comment by uwolfer** [comment]
You are right, this is not implemented in this lib. PRs are very welcome.

Entry points:
* com.google.gerrit.extensions.api.changes.ChangeApi#comments
* com.urswolfer.gerrit.client.rest.http.changes.ChangeApiRestClientTest

**Comment by uwolfer** [comment]
@cbaldacin: I'll close this issue since I have not heard from anybody else about this issue. If you have any feedback / news, please add it here.

**Comment by cbaldacin** [comment]
ok, close it..!
