### ISSUE TITLE
Error 401 in digest authentication after upgrade of Gerrit version to 2.12.2

### ISSUE THREAD

**Issue by NaveenNNK** [uwolfer/gerrit-rest-java-client#45]
First query works fine with Status code 200 but from next time it returns 401. Same code was working till previous version of Gerrit.

**Comment by uwolfer** [comment]
@NaveenNNK: What was the version of Gerrit before the update?

**Comment by falbrech-hsdg** [comment]
Same problem here (if I understand @NaveenNNK correctly): First request (getting files from a change) works fine, but posting a review fails with 401. With same user, everything works fine via Gerrit UI. Using [sputnik](https://github.com/TouK/sputnik) which uses your library, and using Gerrit 2.12.2.

**Comment by falbrech-hsdg** [comment]
Hmm, after updating the sputnik dependency to gerrit-rest-java-client from 0.8.5 to 0.8.8, everything works fine! So I will open an issue there instead.
