### ISSUE TITLE
RestAPI request fails

### ISSUE THREAD

**Issue by FloOows** [uwolfer/gerrit-rest-java-client#66]
Hi,
I am using [Sonar Gerrit Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Sonar+Gerrit) to post score and comment from Jenkins to Gerrit. However, the plugin fails because of a Rest API exception. The exception is in the attached file : [RestAPIException.txt](https://github.com/uwolfer/gerrit-rest-java-client/files/651332/RestAPIException.txt)

I am wondering what is the root cause of this ? Is there a way to get some logs ? Is it possible to know the user used ? Is it the one defined in [Gerrit-Trigger configuration of Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Gerrit+Trigger#GerritTrigger-SettinguptheRESTapi) ?

**Comment by uwolfer** [comment]
@FloOows: The relevant line is:
`Caused by: java.net.SocketTimeoutException: Read timed out`

Most probably, your server is busy or not reachable at configured address / port.

**Comment by FloOows** [comment]
I don't understand because when I am testing the Rest Connection under configuration page (JenkinsIP:8080/gerrit-trigger/server/Gerrit/) I got Success message
![image](https://cloud.githubusercontent.com/assets/14837771/22835970/f0e819e8-efba-11e6-8363-a63dbcbd3252.png)

**Comment by uwolfer** [comment]
@FloOows: Can you reproduce this issue? Probably it also happens only for "heavy" requests like listing a lot of files?

**Comment by FloOows** [comment]
Hi @uwolfer, It is 100% reproducible. I am working on a very small test project containing 2 files.
My config is : Gerrit on a linux server and Jenkins on a Windows server. I am able to ping linux server from windows one.

**Comment by FloOows** [comment]
Is the testing of Rest API may be different than when a plugin try to post something onto gerrit ?

**Comment by uwolfer** [comment]
@FloOows: What do you mean with "testing of Rest API"? The button in Jenkins config UI?

**Comment by FloOows** [comment]
@uwolfer Yes, using "Test REST Connection" button under Gerrit trigger configuration page

**Comment by uwolfer** [comment]
@FloOows: I cannot answer this question. I think you should ask the Jeninks Gerrit plugin authors. Please post any news here. Thank you.

**Comment by FloOows** [comment]
I investigated a little bit more and I have a new question about this issue I still have. I agree with you that this plugin is probably not the root of my issue, but I need to understand something.

1/ Test Rest Connection works from Jenkins -> Manage -> Gerrit Trigger -> Rest Api section
This sends following request to Gerrit : `"GET /a/projects/?d HTTP/1.1" 200 739 - "Apache-HttpClient/4.5.3 (Java/1.8.0_20)"` and return Success into the interface.

2/ While using a tiers plugin, the code and up in your own function [RevisionApiRestClient.files()](https://github.com/uwolfer/gerrit-rest-java-client/blob/b7a7b74048828120c7e03f34acdd801f22a2b3ac/src/main/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClient.java#L170). From here, you call `GerritRestClient.getRequest()` then [GerritRestClient.requestJson()](https://github.com/uwolfer/gerrit-rest-java-client/blob/b7a7b74048828120c7e03f34acdd801f22a2b3ac/src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java#L156) which raise Request Fail exception (main source : java.net.SocketTimeoutException: Read timed out). 

**My understanding :** The request failed because of a time out exception, linked to my environment.

**My question :** Do you know why is it working when I used "Test Rest Connection" button but not in GerritRestClient.java ? Do you use the same mechanism used to send the request then in test button ? 
For your information, the function launched when we click on the button is [there](https://github.com/jenkinsci/gerrit-trigger-plugin/blob/76f654c73d10076cd05b48dd933578b4963a87eb/src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/GerritServer.java#L788).

It would be nice if you could explain this to me.
Thanks

**Comment by uwolfer** [comment]
Are you sure you are using this library? At least the user agent (`Apache-HttpClient/4.5.3 (Java/1.8.0_20)`) is not the one sent by this library. See this code: https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java#L565

You could also look into webserver logs and try to execute the request which fails by your own with `curl`.

The [link](https://github.com/jenkinsci/gerrit-trigger-plugin/blob/76f654c73d10076cd05b48dd933578b4963a87eb/src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/GerritServer.java#L788) you have posted seems not to be related to this library?! I executes a HTTP request directly with `HttpClient`.

**Comment by FloOows** [comment]
Your advice to test it with curl made me point out the issue. It was the classical proxy issue ...
Thanks for your answers.
