### ISSUE TITLE
Need to calculate review time for Gerrit

### ISSUE THREAD

**Issue by rohitthe** [uwolfer/gerrit-rest-java-client#68]
Hi,

Can anybody tell how can i calculate review time from this ?
I was planning to use /detail REST call but dint find any method for it. I need to have time at which reviewer gave +2 to the code.

Could anybody please tell me how to code for detail of changes or any other alternative to get review time?

**Comment by uwolfer** [comment]
IMHO this question isn't specific for this library - you'd better ask this on Gerrit mailing list:
https://groups.google.com/group/repo-discuss

This library just accesses existing Gerrit REST endpoints.
