### ISSUE TITLE
Sortkey not working?

### ISSUE THREAD

**Issue by ishepard** [uwolfer/gerrit-rest-java-client#73]
Hi,
I am aware of the gerrit limit of 500 changes per query. However, according to the APIs, the last change of the list should contain a sortkey to continue from that particular change.

When I run it, sortkey of the last element is null.

Here the code:
```
List<ChangeInfo> changes = gerritApi.changes().query(status).withOptions(ListChangesOption.ALL_FILES, ListChangesOption.ALL_REVISIONS, ListChangesOption.DETAILED_ACCOUNTS).get();
System.out.println("Size: " + changes.size());
ChangeInfo test = changes.get(changes.size() - 1);        
System.out.println("Key: " + test._sortkey);
System.out.println("More changes: " + test._moreChanges);
```

The output is:
```
Size: 500
Sortkey: null
More changes: true
```

What am I wrong?

**Comment by uwolfer** [comment]
What's the version of your Gerrit server? Most probably it's too new.

See: http://stackoverflow.com/questions/24606079/gerrit-rest-api-cannot-use-sortkey-to-resume-a-query

**Comment by uwolfer** [comment]
@ishepard: Due to missing feedback, I'm closing this issue. Feel free to add feedback.
