### ISSUE TITLE
Gerrit Api for Changes return "null" for several attributes 

### ISSUE THREAD

**Issue by atiasadir** [uwolfer/gerrit-rest-java-client#76]
Hi All,

I tried this snippet (based on the given example "Basic.groovy")

List<ChangeInfo> changes = gerritApi.changes().query('is:open+project:syssw/jenkins+branch:ci_devel+label:verified=0').withLimit(2).get()

changes.each { ci ->
    println "subject  => ${ci.subject}"
    println "project  => ${ci.project}"
    println "revisions       => ${ci.revisions}"
    println "currentRevision => ${ci.currentRevision}"
}

Output:
subject  => my_subject for example
project => my_tes_project
_number  => 43239
revisions       => null
currentRevision => null

I think that the parsing of the json output is not accurate.
there are several json responses.

reference https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#get-change-detail
 
also I noticed that "currentRevision" should be "current_revision".

**Comment by uwolfer** [comment]
I think you just need to use option 'ALL_REVISIONS' in your query request (another method like 'withLimit').

**Comment by atiasadir** [comment]
Hi @uwolfer , you are right.
the relevant for example:
gerritApi.changes().query('is:open').withOption(ListChangesOption.CURRENT_REVISION)withLimit(2).get()

another question, is it possible to integrate this awesome library to jenkins ?

**Comment by uwolfer** [comment]
@atiasadir: I do not know Jenkins well. Probably the library could be added as a plugin? I suggest you ask a developer who is familiar with Jenkins ;)
