### ISSUE TITLE
XSRF_TOKEN

### ISSUE THREAD

**Issue by jdktomcat** [uwolfer/gerrit-rest-java-client#78]
Hello,I have a very odd problem for help.Same user and password,one can connect,one not.
![image](https://user-images.githubusercontent.com/8428408/32264573-4e10021e-bf1a-11e7-9fb7-0287b30e0111.png)
![image](https://user-images.githubusercontent.com/8428408/32264593-5cecd79e-bf1a-11e7-8320-56112b6f6f6a.png)
I use the Fiddler analysis the http information,I found the fail reason is missing XSRF_TOKEN cookie
![image](https://user-images.githubusercontent.com/8428408/32264753-12861a8e-bf1b-11e7-8267-df677d49fa85.png) and I don't know why
Please help

**Comment by uwolfer** [comment]
@jdktomcat: Does one user use the "HTTP Password" set in Gerrit settings while the other uses "normal" Gerrit credentials?

**Comment by jdktomcat** [comment]
I try it too,it's also doesn't work

**Comment by jdktomcat** [comment]
intellij14 works fine,but intellij2016.2 and intellij15 fail.I debug the source code,it's the cookie XSRF_TOKEN missing leads this problem

**Comment by uwolfer** [comment]
Just to ensure that I have understood it correctly: It works for the same user with the same password in IntelliJ 14, but it does not work in 15 and 2016.2?

**Comment by jdktomcat** [comment]
@uwolfer yes,it is.But I tried the 2017.2 version,it's work well.Wierd！！

**Comment by uwolfer** [comment]
@jdktomcat: So I'll close this issue because it works now for you.
