### ISSUE TITLE
there is a problem with the date  format 2006-01-02[ 15:04:05[.890][ -0700]]

### ISSUE THREAD

**Issue by samalg91** [uwolfer/gerrit-rest-java-client#79]
i am having thError Getting Gerrit Changes.Request not successful. Message: Bad Request. Status-Code: 400. Content: line 1:56 no viable alternative at character '['.is issue

**Comment by uwolfer** [comment]
Please access the REST API with a plain browser and post the relevant parts of the response there.

**Comment by uwolfer** [comment]
@samalg91: Closing due to missing feedback. Feel free to reopen.
