### ISSUE TITLE
owner.name  always return null

### ISSUE THREAD

**Issue by samalg91** [uwolfer/gerrit-rest-java-client#80]

**Comment by uwolfer** [comment]
Most probably this depends on your Gerrit server. Please request the JSON result with a HTTP client (e.g. curl or your web browser and check if this property is available there.

**Comment by samyzemmouri** [comment]
could you give  me the url i can use  please

**Comment by uwolfer** [comment]
@samyzemmouri: Which API method are you calling? Then I can tell you.

You can find URLs here: https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html

**Comment by uwolfer** [comment]
@samalg91: Do you have some news?

**Comment by uwolfer** [comment]
@samalg91: Feel free to reopen.
