### ISSUE TITLE
How to get Diff between patches

### ISSUE THREAD

**Issue by EFregnan** [uwolfer/gerrit-rest-java-client#84]
Hi, I am new to this API and I would like to extract some information about the diff between two patch sets (or between files in the patch sets). 
I have seen that this project implements the classes DiffInfo and DiffWebLinkInfo, but I can't understand how can I link to them from the information that I obtain using the class GerritApi.

Could you please help me?

Thank you very much.

**Comment by uwolfer** [comment]
You can use the file API: https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/main/java/com/google/gerrit/extensions/api/changes/FileApi.java#L29

(select a change with change API, then get a revision and from there select a file)

If you have any code example which does not work, feel fee to post it here so I can help you.

**Comment by uwolfer** [comment]
You might also want to look into this PR which touches code related to your question: https://github.com/uwolfer/gerrit-rest-java-client/pull/85
