### ISSUE TITLE
use fileApi to send diffrequest get 404 fail

### ISSUE THREAD

**Issue by liliVicky** [uwolfer/gerrit-rest-java-client#87]
I use the following way to get diffInfo, the param file is "src/server/api/v1/router.py" like this, it will be encoded by URLEncoder to "src%2Fserver%2Fapi%2Fv1%2Frouter.py",then send this path to url as a http request ,the http.request in httpcontext is “{http.request=GET /a/changes/292672/revisions/34736b70222534bae851f0455fcf53ef6b731d72/files/cps/server/api/v1/router.py/diff HTTP/1.1”， and i get 404 fail say "not found server". I guess it may because the http.request in httpcontext should be “{http.request=GET /a/changes/292672/revisions/34736b70222534bae851f0455fcf53ef6b731d72/files/cps%2Fserver%2Fapi%2Fv1%2Frouter.py/diff HTTP/1.1”, because when the file param is "config_rc_v1.c",there is not "/" in it , the response is 200, and i get vaild diffInfo. So i submit the issue , hope you can help me, thank you very much!
![image](https://user-images.githubusercontent.com/20653950/54585155-5842ec80-4a54-11e9-8e8a-ac0a77fa3305.png)

![image](https://user-images.githubusercontent.com/20653950/54585195-6e50ad00-4a54-11e9-8ced-6e1c8be772ce.png)

![image](https://user-images.githubusercontent.com/20653950/54585213-7a3c6f00-4a54-11e9-8b36-4288000ca810.png)
![image](https://user-images.githubusercontent.com/20653950/54585244-87595e00-4a54-11e9-908e-6088c1d0df03.png)
![image](https://user-images.githubusercontent.com/20653950/54586142-16677580-4a57-11e9-8978-9efc86884b5f.png)
![image](https://user-images.githubusercontent.com/20653950/54585285-a35cff80-4a54-11e9-8024-9f96c24c745f.png)
![image](https://user-images.githubusercontent.com/20653950/54585302-aa840d80-4a54-11e9-9d06-a85b2bcd5a33.png)

**Comment by uwolfer** [comment]
After shortly looking into the code, I think it should be encoded: https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/main/java/com/urswolfer/gerrit/client/rest/http/changes/FileApiRestClient.java#L50

Since you are already debugging the code: please just download the sources of this lib (available via maven as well), and debug into the lines I've posted above.

**Comment by liliVicky** [comment]
> After shortly looking into the code, I think it should be encoded: https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/main/java/com/urswolfer/gerrit/client/rest/http/changes/FileApiRestClient.java#L50
> 
> Since you are already debugging the code: please just download the sources of this lib (available via maven as well), and debug into the lines I've posted above.

I have debuged into the lines,and got the correct encoded path,but when I send the path to httpclient,httpclient decode it,which I think is the reason for the problem.I have used httpurlconnection instead of httpclient which won’t decode path before send to get responses to solve the problem and I think you should also modify it in your project.

**Comment by uwolfer** [comment]
@liliVicky: I've received feedback from another user that building with Java 8 (or later) fixes this issue. Could you try that? You probably need to update the language and target level in maven XML file.

**Comment by liliVicky** [comment]
I've used java 8, but still have the problem.
![image](https://user-images.githubusercontent.com/20653950/58066171-ce7ddf80-7bba-11e9-81b4-d7ebaa86a166.png)

**Comment by uwolfer** [comment]
@liliVicky: Thanks. Can you please also try to change the target level (project bytecode level)? See: https://stackoverflow.com/a/12900859

**Comment by uwolfer** [comment]
Closing due to missing feedback.
