### ISSUE TITLE
Threadsafety of Library?

### ISSUE THREAD

**Issue by PowerLiam** [uwolfer/gerrit-rest-java-client#90]
Hello!

I was interested in some information regarding the threadsafety of this library (the GerritApi object).  I did some reading of the source and found some low level locking (in CookieStore for example), but I wanted to make sure that the library is considered threadsafe in its entirety.  How will it handle 15-20 threads pounding the same GerritApi object?

Also as a sidenote, is it safe to have multiple GerritApi objects floating around in the wild (do they share any static non-threadsafe members?)

Thank you very much for your time, and for creating this library.

Liam.

**Comment by uwolfer** [comment]
I think it should be thread safe.

One thing which probably not plays very nicely, is [LoginCache](https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/main/java/com/urswolfer/gerrit/client/rest/http/LoginCache.java), but it should not cause any issues.

> Also as a sidenote, is it safe to have multiple GerritApi objects floating around in the wild (do they share any static non-threadsafe members?)

That should also work. The cache mentioned above is not shared, but it works nevertheless.

If you find any issues, please let me know.
