### ISSUE TITLE
Incompatibility with Gerrit <= v2.14

### ISSUE THREAD

**Issue by lucamilanesio** [uwolfer/gerrit-rest-java-client#97]
When using the Java client with Gerrit v2.14 (or earlier) the ChangeApiRestClient.get() would cause Gerrit to fail with the following error: `com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful. Message: Bad Request. Status-Code: 400. Content: "TRACKING_IDS" is not a valid value for "-o".`.

This is causing the Gerrit Code Review plugin for Jenkins to fail (see reported Issue [JENKINS-60364](https://issues.jenkins-ci.org/browse/JENKINS-60364)).

**Comment by lucamilanesio** [comment]
@uwolfer I believe the problem is related to https://github.com/uwolfer/gerrit-rest-java-client/blob/c08c7631e2ddf2af2fb510d1186500395a784ff2/src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java#L281.
By adding *ALL* options you are adding also the ones that aren't supported in v2.14, like TRACKING_IDS.

**Comment by lucamilanesio** [comment]
@uwolfer I believe the solution would be:
1. Get the remote Gerrit version
2. Remove ALL extensions that are bigger than the highest extension available on that version

How does it sound?

**Comment by lucamilanesio** [comment]
In the README.md you stated `Only Gerrit 2.6 or newer is supported`: would you like possibly to revisit the statement and include only a more recent release? Let's say v2.10 or later? That would reduce the impact of the fix.

**Comment by uwolfer** [comment]
@lucamilanesio: Thanks for your detailed report.

I'm just wondering if you really need to call `#get()`? I'd suggest to call `#get(EnumSet<ListChangesOption> options)` also for performance reasons if you do not really need all of the details.

In the Gerrit IntelliJ plugin, I've used this workaround for Gerrit backwards compatibility: https://github.com/uwolfer/gerrit-intellij-plugin/blob/intellij14/src/main/java/com/urswolfer/intellij/plugin/gerrit/rest/GerritUtil.java#L454-L470

I agree, one possibility could be to fetch the Gerrit version, and then only use options which are supported. But I think in most cases, it makes sense to specify required options anyway.

**Comment by lucamilanesio** [comment]
> @lucamilanesio: Thanks for your detailed report.
> 
> I'm just wondering if you really need to call `#get()`? I'd suggest to call `#get(EnumSet<ListChangesOption> options)` also for performance reasons if you do not really need all of the details.

I need all the change details because they are needed to setup the environment variables used by the job. I will also expose the change data as JSON object to the pipeline.

> In the Gerrit IntelliJ plugin, I've used this workaround for Gerrit backwards compatibility: https://github.com/uwolfer/gerrit-intellij-plugin/blob/intellij14/src/main/java/com/urswolfer/intellij/plugin/gerrit/rest/GerritUtil.java#L454-L470

Saw that, however, it's a bit of a shoot in the dark isn't it? I'd prefer to have a clearer definition of what is and is not included in the version of Gerrit that the API is calling.

> I agree, one possibility could be to fetch the Gerrit version, and then only use options which are supported. But I think in most cases, it makes sense to specify required options anyway.

True, but that option may not be available anyway in the version of Gerrit.
It would be best IMHO to have the Gerrit client API to manage that complexity rather than having all the applications having to deal with it.

BTW I was planning to fix the problem if you would have some time to review it :-) Thanks again for writing this Java client layer, it is very useful indeed.

**Comment by uwolfer** [comment]
> > @lucamilanesio: Thanks for your detailed report.
> > I'm just wondering if you really need to call `#get()`? I'd suggest to call `#get(EnumSet<ListChangesOption> options)` also for performance reasons if you do not really need all of the details.
> 
> I need all the change details because they are needed to setup the environment variables used by the job. I will also expose the change data as JSON object to the pipeline.

I see, makes sense.

> > In the Gerrit IntelliJ plugin, I've used this workaround for Gerrit backwards compatibility: https://github.com/uwolfer/gerrit-intellij-plugin/blob/intellij14/src/main/java/com/urswolfer/intellij/plugin/gerrit/rest/GerritUtil.java#L454-L470
> 
> Saw that, however, it's a bit of a shoot in the dark isn't it? I'd prefer to have a clearer definition of what is and is not included in the version of Gerrit that the API is calling.

Yes, this is a fallback which works in my specific case because I can handle it when some data is not available.

> > I agree, one possibility could be to fetch the Gerrit version, and then only use options which are supported. But I think in most cases, it makes sense to specify required options anyway.
> 
> True, but that option may not be available anyway in the version of Gerrit.
> It would be best IMHO to have the Gerrit client API to manage that complexity rather than having all the applications having to deal with it.

I'm just wondering what happens when an option is requested, but the client knows that this option is not supported by the Gerrit server which is connected?

> BTW I was planning to fix the problem if you would have some time to review it :-) Thanks again for writing this Java client layer, it is very useful indeed.

Sounds good - I'm happy to review it.

**Comment by lucamilanesio** [comment]
> > True, but that option may not be available anyway in the version of Gerrit.
> > It would be best IMHO to have the Gerrit client API to manage that complexity rather than having all the applications having to deal with it.
> 
> I'm just wondering what happens when an option is requested, but the client knows that this option is not supported by the Gerrit server which is connected?

I was thinking about exposing the list of supported options for the current detected version of the server that the client is connected to. Then, even after knowing them, if the client is *explicitly* using an unsupported option, he will get an exception, which is expected.

If no options are passed,  the client will get all the possible options supported by the remote Gerrit server version.

Hope that would make sense.

**Comment by uwolfer** [comment]
> > > True, but that option may not be available anyway in the version of Gerrit.
> > > It would be best IMHO to have the Gerrit client API to manage that complexity rather than having all the applications having to deal with it.
> > 
> > 
> > I'm just wondering what happens when an option is requested, but the client knows that this option is not supported by the Gerrit server which is connected?
> 
> I was thinking about exposing the list of supported options for the current detected version of the server that the client is connected to. Then, even after knowing them, if the client is _explicitly_ using an unsupported option, he will get an exception, which is expected.
> 
> If no options are passed, the client will get all the possible options supported by the remote Gerrit server version.
> 
> Hope that would make sense.

Sounds good.

**Comment by lucamilanesio** [comment]
@uwolfer this is now fixed on master, is it possible to have a release?

**Comment by uwolfer** [comment]
@lucamilanesio I've released it as 0.9.0.

**Comment by lucamilanesio** [comment]
Thanks @uwolfer for your help in getting this merged and released :-)
